SELECT
			CAST(EDW_PROCESS.SEQ_MASTER_MEMBER_ID_H0.NEXTVAL AS BIGINT) AS ADDRESS_PHYSICAL_ID,
			CAST(''Y'' AS VARCHAR(1 OCTETS)) AS ACTIVE_FLAG,
			CAST(''1900-01-01-00.00.00'' AS TIMESTAMP) AS EFFECTIVE_START_DATETIME,
			CAST(NULL AS TIMESTAMP) AS EFFECTIVE_END_DATETIME,
			CAST(HASH(CAST(
				COALESCE(COALESCE(TRIM(dbarcud.ADDR2), ''''), ''#'') || ''&'' ||
				COALESCE(COALESCE(TRIM(dbarcud.ADDR1), ''''), ''$'') || ''&'' ||
				''@'' || ''&'' ||
				COALESCE(COALESCE(TRIM(dbarcud.CITY), ''''), ''D'') || ''&'' ||
				COALESCE(LEFT(LEFT(REPLACE(TRIM(REPLACE(TRIM(dbarcud.ZIP), ''-'', '' '')), '' '', '''') || ''000000000'', 9), 5), ''E'') || ''&'' ||
				COALESCE(RIGHT(LEFT(REPLACE(TRIM(REPLACE(TRIM(dbarcud.ZIP), ''-'', '' '')), '' '', '''') || ''000000000'', 9), 4), ''F'') || ''&'' ||
				COALESCE(COALESCE(TRIM(dbarcud.STATE), ''''), ''G'') || ''&'' ||
				COALESCE(CASE
					WHEN TRIM(dbarcud.COUNTRY_CODE) = '''' THEN ''US''
					ELSE TRIM(dbarcud.COUNTRY_CODE)
				END, ''H'') AS VARCHAR), 3) AS VARBINARY(64)) AS LOOKUP_HASH_ADDRESS_PHYSICAL,
			CAST(TRIM(dbarcud.ADDR2) AS VARCHAR(128 OCTETS)) AS PHYSICAL_ADDRESS_LINE_1,
			CAST(COALESCE(TRIM(dbarcud.ADDR1), '''') AS VARCHAR(128 OCTETS)) AS PHYSICAL_ADDRESS_LINE_2,
			CAST('''' AS VARCHAR(128 OCTETS)) AS PHYSICAL_ADDRESS_SUITE,
			CAST(TRIM(dbarcud.CITY) AS VARCHAR(128 OCTETS)) AS PHYSICAL_ADDRESS_CITY,
			CAST(LEFT(LEFT(REPLACE(TRIM(REPLACE(TRIM(dbarcud.ZIP), ''-'', '' '')), '' '', '''') || ''000000000'', 9), 5) AS VARCHAR(5)) AS PHYSICAL_ADDRESS_POSTAL_CODE,
			CAST(RIGHT(LEFT(REPLACE(TRIM(REPLACE(TRIM(dbarcud.ZIP), ''-'', '' '')), '' '', '''') || ''000000000'', 9), 4) AS VARCHAR(64 OCTETS)) AS PHYSICAL_ADDRESS_POSTAL_CODE_EXTENSION,
			CAST(TRIM(dbarcud.STATE) AS VARCHAR(64 OCTETS)) AS PHYSICAL_ADDRESS_STATE_PROVINCE_CODE,
			CAST(CASE
				WHEN TRIM(dbarcud.COUNTRY_CODE) = '''' THEN ''US''
				ELSE TRIM(dbarcud.COUNTRY_CODE)
			END AS VARCHAR(512 OCTETS)) AS PHYSICAL_ADDRESS_COUNTRY_CODE,
			CAST(''N'' AS VARCHAR(1 OCTETS)) AS PHYSICAL_ADDRESS_STORE_ADDRESS_FLAG,
			CAST(''N'' AS VARCHAR(1 OCTETS)) AS PHYSICAL_ADDRESS_VERIFICATION_FLAG,
			CAST(''N'' AS VARCHAR(1 OCTETS)) AS PHYSICAL_ADDRESS_ANONIMZATION_FLAG,
			CAST(COALESCE(hub_load_DIM_GEOGRAPHY_POSTAL.GEOGRAPHY_ID, -2) AS BIGINT) AS GEOGRAPHY_ID,
			CAST(0.0 AS DECIMAL(13,7)) AS PHYSICAL_ADDRESS_LATITUDE,
			CAST(0.0 AS DECIMAL(13,7)) AS PHYSICAL_ADDRESS_LONGITUDE,
			CAST(''N'' AS VARCHAR(1 OCTETS)) AS ETL_SOURCE_DATA_DELETED_FLAG,
			CAST(' || quote_literal(v_etl_source_table_3) || ' AS VARCHAR(256 OCTETS)) AS ETL_SOURCE_TABLE_NAME,
			CAST(CURRENT_TIMESTAMP - CURRENT_TIMEZONE AS TIMESTAMP) AS ETL_CREATE_TIMESTAMP,
			CAST(CURRENT_TIMESTAMP - CURRENT_TIMEZONE AS TIMESTAMP) AS ETL_UPDATE_TIMESTAMP,
			CAST(' || v_stored_procedure_execution_id || ' AS BIGINT) AS ETL_MODIFIED_BY_JOB_ID,
			CAST(' || quote_literal(v_hub_procedure_name) || ' AS VARCHAR(128 OCTETS)) AS ETL_MODIFIED_BY_PROCESS
		FROM {{ source('edw_staging', 'CUR_CUS_DBARCUD') }} dbarcud
		INNER JOIN {{ source('edw_staging', 'CUR_CUS_MASTER') }} cmaster
			ON CAST(cmaster.CCUST# AS VARCHAR) = TRIM(dbarcud.CUSTOMER)